version: '3.4'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3308:3306
    volumes:
      - mysqldata:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mysqldata:
  rabbitmqdata:
